//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Holiday.Core.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Values {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Values() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LS.Holiday.Core.Strings.Values", typeof(Values).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ksiegowosc@future-processing.com.
        /// </summary>
        public static string AccountancyMailAddress {
            get {
                return ResourceManager.GetString("AccountancyMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request has been approved - {0}..
        /// </summary>
        public static string AccountancyNotificationMailContent {
            get {
                return ResourceManager.GetString("AccountancyNotificationMailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Request - Accountancy Notification.
        /// </summary>
        public static string AccountancyNotificationMailHeader {
            get {
                return ResourceManager.GetString("AccountancyNotificationMailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Vacation: {0}.
        /// </summary>
        public static string CalendarMailHeader {
            get {
                return ResourceManager.GetString("CalendarMailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to europa_centralna@future-processing.com.
        /// </summary>
        public static string HolidayServiceMailAddress {
            get {
                return ResourceManager.GetString("HolidayServiceMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have new holiday approval request: {0}.
        /// </summary>
        public static string LeaderApprovalRequestMailContent {
            get {
                return ResourceManager.GetString("LeaderApprovalRequestMailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Request -  from {0}.
        /// </summary>
        public static string LeaderApprovalRequestMailHeader {
            get {
                return ResourceManager.GetString("LeaderApprovalRequestMailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your holiday request status: {0}.
        /// </summary>
        public static string LeaderResponseMailContent {
            get {
                return ResourceManager.GetString("LeaderResponseMailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Request - Project Leader Response.
        /// </summary>
        public static string LeaderResponseMailHeader {
            get {
                return ResourceManager.GetString("LeaderResponseMailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available..
        /// </summary>
        public static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urlopy@future-processing.com.
        /// </summary>
        public static string PublicCalendarMailAddress {
            get {
                return ResourceManager.GetString("PublicCalendarMailAddress", resourceCulture);
            }
        }
    }
}
