//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Holiday.Core.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Values {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Values() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LS.Holiday.Core.Strings.Values", typeof(Values).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Approved Holiday.
        /// </summary>
        public static string AccountancyHolidaySubject {
            get {
                return ResourceManager.GetString("AccountancyHolidaySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ksiegowosc@future-processing.com.
        /// </summary>
        public static string AccountancyMail {
            get {
                return ResourceManager.GetString("AccountancyMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Vacation: {0}.
        /// </summary>
        public static string HolidayCalendarTitle {
            get {
                return ResourceManager.GetString("HolidayCalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your holiday request has been {0}..
        /// </summary>
        public static string HolidayRequestAnswer {
            get {
                return ResourceManager.GetString("HolidayRequestAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays Approval Request from {0}.
        /// </summary>
        public static string HolidaysApprovalRequest {
            get {
                return ResourceManager.GetString("HolidaysApprovalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to europa_centralna@future-processing.com.
        /// </summary>
        public static string HolidayServiceMail {
            get {
                return ResourceManager.GetString("HolidayServiceMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urlopy@future-processing.com.
        /// </summary>
        public static string PublicCalendarAddress {
            get {
                return ResourceManager.GetString("PublicCalendarAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your holiday request has been processed..
        /// </summary>
        public static string RequestProcessedSubject {
            get {
                return ResourceManager.GetString("RequestProcessedSubject", resourceCulture);
            }
        }
    }
}
